music_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :bands

  resources :bands, only: [] do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index]

  resources :albums, only: [] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index]
end

music_app/app/models/album.rb
class Album < ActiveRecord::Base
  validates :title, :band_id, presence: true

  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :track,
    class_name: "Track",
    foreign_key: :album_id,
    primary_key: :id,
    dependent: :destroy
  )
end

music_app/app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many(
    :albums,
    class_name: "Album",
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy
  )

end

music_app/app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to(
    :album,
    class_name: "Album",
    foreign_key: :album_id,
    primary_key: :id
  )

  has_one(
    :band,
    through: :album,
    source: :band
  )
end

music_app/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :email, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :generate_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def generate_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @bands = Band.all
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      redirect_to new_band_album_url
    end
  end

  def destroy
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update

  end

  def album_params
    params.require(:album).permit(:title, :band_id, :live_or_studio)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def logged_in?(user)
    session[:session_token] == user.session_token
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout!
    session[:session_token] = nil
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def destroy
    Band.destroy(params[:id])
    redirect_to bands_url
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.update(params[:id], band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      redirect_to edit_band_url
    end
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:email], user_params[:password])
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
    @track = Track.new
    render :new
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
    end
  end

  def destroy
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.update(params[:id], track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      redirect_to edit_track_url(@track)
    end
  end

  def track_params
    params.require(:track).permit(:song_name)
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
end

music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/tracks_helper.rb
module TracksHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/albums/new.html.erb
<h1>Add a new record to the discography</h1>

<form action="<%= albums_url %>" method="post">

  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="album_title">Album Title</label>
    <input type="text" name="album[title]" value="<%= @album.title %>">

  <label for="album_band_id">Band Name</label>

    <select name="album[band_id]">
      <% @bands.each do |band|  %>
        <option name="album[band_id]"
                value="<%= band.id %>"><%= band.name %></option>
                <% @album.band_id = band.id %>
      <% end %>
    </select>

  <br>
  <br>

  <label for="album_live_or_studio"></label>
    <input type="radio" name="album[live_or_studio]"
           id="album_live_or_studio"
          value="live">Live recording<br>
    <input type="radio" name="album[live_or_studio]"
           id="album_live_or_studio"
          value="studio">Studio recording<br>

  <br>
  <input type="submit" value="Add album">
</form>

music_app/app/views/albums/show.html.erb
<h1><%= @album.title %></h1>

<% @band = Band.find(@album.band_id) %>
<%= link_to "<< #{@band.name}", band_url(@band) %>
<br>
<br>
<%= button_to "Edit page", edit_album_url(@album) %>
<%= button_to "Delete album", album_url(@album), method: :delete %>

music_app/app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <label for="band_name"></label>
  <input type="text" name="band[name]"
         id="band_name"
         value="<% @band.name %>">
  <input type="submit" value="Save Edits">
</form>

music_app/app/views/bands/index.html.erb
<h1>All the bands</h1>

<% @bands.all.each do |band| %>
  <li><%= link_to band.name, band_url(band) %></li>
<% end %>

music_app/app/views/bands/new.html.erb
<h1>List a new band</h1>

<form action="<%= bands_url %>" method="post">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="band_name"></label>
  <input type="text" name="band[name]"
         id="band_name"
         value="<% @band.name %>">
         
  <input type="submit" value="Add Band">
</form>

music_app/app/views/bands/show.html.erb
<h1><%= @band.name %> rocks!</h1>

<%= link_to "<< All bands ", bands_url %>
<br>
<br>

<% @band.albums.each do |album| %>
  <li><%= link_to album.title, album_url(album) %></li>
<% end %>

<br>

<%= button_to "Edit page", edit_band_url(@band) %>
<%= button_to "Delete band", band_url(@band), method: :delete %>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= current_user %>
<% if current_user %>
  <h1>
    <%= "Hello  #{current_user.email}!"%>
  </h1>
  <%= button_to "Log Out", session_url(current_user.id), method: :delete %>
<% else %>
  <%= "Please log in!" %>
<% end %>

<%= yield %>

</body>
</html>

music_app/app/views/tracks/edit.html.erb
<h1>Edit <%= @track.song_name %></h1>

<form action="<%= track_url(@track) %>" method="post">

  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="track_song_name">Song Name</label>
  <input type="text" name="track[song_name]"
         id="track_song_name"
         value="<%= @track.song_name %>">

  <br>
  <br>

  <label for="track_bonus_or_regular"></label>
  <input type="radio" name="track[bonus_or_regular]"
         id="track_bonus_or_regular"
         value="bonus">Bonus
  <input type="radio" name="track[bonus_or_regular]"
         id="track_bonus_or_regular"
         value="regular">Regular

  <br>
  <br>

  <label for="track_lyrics">Lyrics</label><br>
    <textarea name="track[lyrics]" rows="8" cols="40"></textarea>

  <br>

  <input type="submit" value="Save edits">
</form>

music_app/app/views/tracks/new.html.erb
<h1>Add your hot new track!</h1>

<form action="<%= tracks_url %>" method="post">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="track_song_name">Song Name</label>
  <input type="text" name="track[song_name]"
         id="track_song_name"
         value="<%= @track.song_name %>">

  <br>
  <br>

  <label for="track_bonus_or_regular"></label>
  <input type="radio" name="track[bonus_or_regular]"
         id="track_bonus_or_regular"
         value="bonus">Bonus
  <input type="radio" name="track[bonus_or_regular]"
         id="track_bonus_or_regular"
         value="regular">Regular

  <br>
  <br>

  <label for="track_lyrics">Lyrics</label><br>
    <textarea name="track[lyrics]" rows="8" cols="40"></textarea>

  <br>

  <input type="submit" value="Add track">
</form>

music_app/app/views/tracks/show.html.erb
<h1><%= @track.song_name %> is a hot track</h1>

<% @album = Album.find(@track.album_id) %>
<%= link_to "<< #{@album.title}" %>

<%= button_to "Edit song", edit_track_url(@track) %>
<%= button_to "Delete song", track_url(@track), method: :delete %>

music_app/app/views/users/new.html.erb
<h1>Sign Up!</h1>

<ul>
  <% if flash[:errors] %>
    <% flash[:errors].each do |err_msg| %>
      <li><%= err_msg %></li>
    <% end  %>
  <% end %>
</ul>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="user-email">Email</label>
    <input type="email" name="user[email]" value="<%= @user.email %>">

  <label for="user-password">Password</label>
    <input type="password" name="user[password]" value="<%= %>">

    <input type="submit" value="Create User">
</form>

music_app/app/views/users/show.html.erb
<h1>Hello <%= @user.email %></h1>